# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_Desc', models.TextField()),
                ('Trans_Date', models.DateTimeField()),
                ('Trans_Type', models.CharField(max_length=50)),
                ('Trans_Loc', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=16),
        ),
    ]
