# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTrans', '0003_transaction_trans_amnt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
    ]
