# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTrans', '0004_auto_20170406_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
