# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTrans', '0005_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cate_Type', models.CharField(max_length=50)),
                ('Cate_Desc', models.TextField()),
            ],
        ),
    ]
